global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cbc-node'
    static_configs:
      - targets: ['10.0.2.15:9615']  # Host IP for Substrate metrics port
    scrape_interval: 5s
    metrics_path: /metrics
    honor_labels: true