#!/bin/bash
# Start a generic validator node — for any new node joining the network.
# Keys, directories, and P2P identity are all auto-generated by the node binary.
#
# Usage:
#   NAME=satoshi bash scripts/start_validator.sh
#   NAME=nakamoto PORT=30336 RPC_PORT=9947 bash scripts/start_validator.sh

set -e

BINARY="${BINARY:-./target/release/cbc-node}"
NAME="${NAME:-validator}"
PORT="${PORT:-30336}"
RPC_PORT="${RPC_PORT:-9947}"
PROM_PORT="${PROM_PORT:-9618}"
BASE_PATH="${BASE_PATH:-$HOME/.local/share/cbc-node/$NAME}"
LOG_FILE="${LOG_FILE:-node_output_$NAME.log}"
ALICE_BASE_PATH="${ALICE_BASE_PATH:-$HOME/.local/share/cbc-node/alice}"

if [ ! -f "$BINARY" ]; then
    echo "ERROR: Binary not found at $BINARY. Run: cargo build --release"
    exit 1
fi

# Derive Alice's peer ID from her network key (written by the node on first start).
ALICE_NET_KEY="$ALICE_BASE_PATH/chains/cbc_local/network/secret_ed25519"
MAX_RETRIES=15
RETRY=0

echo "Waiting for Alice's network key at $ALICE_NET_KEY..."
while [ ! -f "$ALICE_NET_KEY" ] && [ $RETRY -lt $MAX_RETRIES ]; do
    sleep 2
    RETRY=$((RETRY + 1))
    echo "  ...attempt $RETRY/$MAX_RETRIES"
done

if [ ! -f "$ALICE_NET_KEY" ]; then
    echo "ERROR: Alice's network key not found. Make sure Alice is running: bash scripts/start_alice.sh"
    exit 1
fi

ALICE_PEER_ID=$("$BINARY" key inspect-node-key --file "$ALICE_NET_KEY" 2>/dev/null | tail -n 1)
if [ -z "$ALICE_PEER_ID" ]; then
    echo "ERROR: Could not derive Alice's peer ID from $ALICE_NET_KEY"
    exit 1
fi

echo "Starting validator '$NAME'..."
echo "  Data dir   : $BASE_PATH"
echo "  RPC port   : $RPC_PORT"
echo "  Bootnode   : /ip4/127.0.0.1/tcp/30333/p2p/$ALICE_PEER_ID"
echo "  Log file   : $LOG_FILE"

exec "$BINARY" \
    --base-path "$BASE_PATH" \
    --chain local \
    --port "$PORT" \
    --rpc-port "$RPC_PORT" \
    --prometheus-port "$PROM_PORT" \
    --prometheus-external \
    --unsafe-rpc-external \
    --rpc-cors all \
    --validator \
    --name "$NAME" \
    --bootnodes "/ip4/127.0.0.1/tcp/30333/p2p/$ALICE_PEER_ID" \
    >> "$LOG_FILE" 2>&1
