#!/bin/bash
# Start all three validator nodes for local DVF testing.
# Keys, directories, and P2P identities are all auto-generated by the node binary.

set -e

BINARY="${BINARY:-./target/release/cbc-node}"

if [ ! -f "$BINARY" ]; then
    echo "ERROR: Binary not found at $BINARY. Run: cargo build --release"
    exit 1
fi

echo "Starting CBC Chain multi-validator network..."
echo "Data dir: ~/.local/share/cbc-node/"
echo ""

# Clean up old logs
rm -f node_output_alice.log node_output_bob.log node_output_charlie.log

# Start Alice first — she is the bootnode.
# Bob and Charlie will wait for her network key before connecting.
bash scripts/start_alice.sh &
ALICE_PID=$!
echo "Alice started (PID: $ALICE_PID) — RPC: 9944, P2P: 30333"

bash scripts/start_bob.sh &
BOB_PID=$!
echo "Bob started (PID: $BOB_PID) — RPC: 9945, P2P: 30334"

bash scripts/start_charlie.sh &
CHARLIE_PID=$!
echo "Charlie started (PID: $CHARLIE_PID) — RPC: 9946, P2P: 30335"

echo ""
echo "Logs:"
echo "  tail -f node_output_alice.log"
echo "  tail -f node_output_bob.log"
echo "  tail -f node_output_charlie.log"
echo ""
echo "To stop all nodes: bash scripts/stop_all.sh"
